
export enum USER_STATUS {
    ACTIVE = "Active",
    INACTIVE = "Inactive"
}
export enum ITEM_STATUS {
    ACTIVE = "Active",
    INACTIVE = "Inactive"
}
export enum ORDER_STATUS {
    PENDING = "Pending",
    ACCEPTED = "Accepted",
    PROCESSING = "Processing",
    OUT_FOR_DELIVERY = "Out for delivery",
    DELIVERED = "Delivered",
    CANCELLED = "Cancelled",
    COMPLETED = "Completed",

}
export enum RESOURCE_PERMISSION {
    USER_DETAILS_CREATE = 'USER_DETAILS_CREATE',
    USER_DETAILS_UPDATE = 'USER_DETAILS_UPDATE',
    USER_DETAILS_VIEW = 'USER_DETAILS_VIEW',
    USER_DETAILS_DELETE = 'USER_DETAILS_DELETE',
    USER_LIST_VIEW = 'USER_LIST_VIEW',
    ROLE_DETAILS_CREATE = 'ROLE_DETAILS_CREATE',
    ROLE_DETAILS_UPDATE = 'ROLE_DETAILS_UPDATE',
    ROLE_DETAILS_VIEW = 'ROLE_DETAILS_VIEW',
    ROLE_DETAILS_DELETE = 'ROLE_DETAILS_DELETE',
    ROLE_LIST_VIEW = 'ROLE_LIST_VIEW',
    ITEM_DETAILS_CREATE = 'ITEM_DETAILS_CREATE',
    ITEM_DETAILS_UPDATE = 'ITEM_DETAILS_UPDATE',
    ITEM_DETAILS_VIEW = 'ITEM_DETAILS_VIEW',
    ITEM_DETAILS_DELETE = 'ITEM_DETAILS_DELETE',
    ITEM_LIST_VIEW = 'ITEM_LIST_VIEW',
    ORDER_CREATE = 'ORDER_CREATE',
    ORDER_UPDATE = 'ORDER_UPDATE',
    ORDER_VIEW = 'ORDER_VIEW',
    ORDER_DELETE = 'ORDER_DELETE',
    ORDER_LIST_VIEW = 'ORDER_LIST_VIEW',
    ALL = 'ALL',

}